onCreate:
  - sudo apt-get update -y
  - sudo apt-get upgrade -y

onStart:
  - |
        WS_DOMAIN=`cat /home/ubuntu/runcode/ws-url-domain.txt`
        printf "\nGO TO THIS URL TO VIEW PAGE \033[4;34m https://5138-${WS_DOMAIN}\033[0;30m\n\n"
        dotnet watch